apps/login/urls.py
from django.urls import path
from login import views

app_name = 'login'

urlpatterns = [
    path('', views.login_view, name='login_SisGECC'), # Aponta a URL raiz para login_view
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),  # Adiciona a rota para logout    
]

apps/painel/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'painel'

urlpatterns = [
    path('', views.painel, name='painel'),
    path('dashboard/<int:id>/', views.dashboard, name='dashboard'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

observatorio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('painel/', include('painel.urls')),
]

apps/login/models.py
from django.db import models

# Create your models here.

apps/painel/models.py
from django.db import models

# Create your models here.
class Dashboard(models.Model):
    nome = models.CharField(max_length=200, verbose_name="Nome")
    descricao = models.TextField(verbose_name="Descrição")
    fonte_dos_dados = models.TextField(verbose_name="Fonte dos Dados")
    utilizacao = models.TextField(verbose_name="Utilização")
    documentacao = models.FileField(upload_to='documentacao/',  null=True, blank=True, verbose_name="Documentação (PDF)")
    data_atualizacao = models.DateField(verbose_name="Data da Atualização")
    link = models.URLField(max_length=500, verbose_name="Link do Dashboard", null=True, blank=True)


    def __str__(self):
        return str(self.nome)

apps/login/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Usuário'})
        self.fields['password'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Senha'})

apps/login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout # Importar a função logout
from django.contrib.auth.decorators import login_required  # Importe o decorator
from login.forms import LoginForm


def login_view(request):
    if request.user.is_authenticated:
        return redirect('painel:painel')  # Redireciona para a página index se já estiver autenticado
    
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST) # Use o formulário personalizado
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('painel:painel') # Redireciona para a página index
            else:
                form.add_error(None, "Usuário ou senha incorretos.")
    else:
        form = LoginForm() # Use o formulário personalizado
    return render(request, 'login/pages/login.html', {'form': form})

def logout_view(request):
    logout(request) # Desloga o usuário
    return redirect('login:login_SisGECC')  # Redireciona para a página de login

apps/painel/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required  # Importe o decorator
from .models import Dashboard  # Importe o modelo Dashboard


# Create your views here.

@login_required
def painel(request):
    dashboards = Dashboard.objects.all()  # Obtém todos os dashboards do banco de dados
    return render(request, 'painel/pages/painel.html', {'dashboards': dashboards})

@login_required
def dashboard(request, id):
    dashboard = get_object_or_404(Dashboard, id=id)  # Valida o ID e retorna 404 se não encontrado
    return render(request, 'painel/partials/dashboard.html', {'dashboard': dashboard})

apps/login/templates/login/pages/index.html
{% extends "global/pages/master-page.html" %}
{% load static %}

<title> GECC | {% block title %} Eventos {% endblock title %} </title>


{% block conteudo %}

    <div class="titulo-sessao-principal">
        <h2>Lista de Processos Abertos</h2>
    </div>

    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <button class="btn btn-primary me-md-2 btn-novo-verde" data-bs-toggle="modal" data-bs-target="#exampleModal" type="button">Novo Processo</button>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>


    <table class="table tabela-relatorio">
        <thead class="table-green-if">
          <tr>
            <th scope="col">Código</th>
            <th scope="col">Nome do Evento</th>
            <th scope="col">Tipo</th>
            <th scope="col">Responsável</th>
            <th scope="col">Período</th>
            <th scope="col">Campus</th>
            <th scope="col">Situação</th>
            <th scope="col">Ações</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>Processo Seletivo de Estudantes dos Cursos Integrados - 2025</td>
            <td>Marcio Alencar</td>
            <td>Concurso</td>
            <td>01/10/2025 até 15/12/2025</td>
            <td>Serrinha</td>                        
            <td>Iniciado</td>                        
            <td><i class="fa fa-search icone-acao icone-consultar" aria-hidden="true"></i><i class="fa fa-pencil icone-acao icone-editar" aria-hidden="true"></i><i class="fa fa-trash icone-acao icone-excluir" aria-hidden="true"></i></td>                        
          </tr>
          <tr>
            <th scope="row">1</th>
            <td>Processo Seletivo de Estudantes dos Cursos Integrados - 2025</td>
            <td>Marcio Alencar</td>                        
            <td>Concurso</td>
            <td>01/10/2025 até 15/12/2025</td>
            <td>Serrinha</td>                        
            <td>Iniciado</td>                        
            <td><i class="fa fa-search icone-acao icone-consultar" aria-hidden="true"></i><i class="fa fa-pencil icone-acao icone-editar" aria-hidden="true"></i><i class="fa fa-trash icone-acao icone-excluir" aria-hidden="true"></i></td>                        
          </tr>
          <tr>
            <th scope="row">1</th>
            <td>Processo Seletivo de Estudantes dos Cursos Integrados - 2025</td>
            <td>Marcio Alencar</td>                        
            <td>Concurso</td>
            <td>01/10/2025 até 15/12/2025</td>
            <td>Serrinha</td>                        
            <td>Iniciado</td>                        
            <td><i class="fa fa-search icone-acao icone-consultar" aria-hidden="true"></i><i class="fa fa-pencil icone-acao icone-editar" aria-hidden="true"></i><i class="fa fa-trash icone-acao icone-excluir" aria-hidden="true"></i></td>                        
          </tr>
        </tbody>
      </table>


{% endblock conteudo %}

{% block javascript %}
    <script src="{% static 'login/js/script.js' %}"></script> 
{% endblock javascript %}

apps/login/templates/login/pages/login.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/brands.min.css" integrity="sha512-58P9Hy7II0YeXLv+iFiLCv1rtLW47xmiRpC1oFafeKNShp8V5bKV/ciVtYqbk2YfxXQMt58DjNfkXFOn62xE+g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/fontawesome.min.css" integrity="sha512-v8QQ0YQ3H4K6Ic3PJkym91KoeNT5S3PnDKvqnwqFD1oiqIl653crGZplPdU5KKtHjO0QKcQ2aUlQZYjHczkmGw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/solid.min.css" integrity="sha512-DzC7h7+bDlpXPDQsX/0fShhf1dLxXlHuhPBkBo/5wJWRoTU6YL7moeiNoej6q3wh5ti78C57Tu1JwTNlcgHSjg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'login/css/style.css' %}">

    <title>OBSERVIF - Login</title>
</head>

<body>
    <div class="container">
        <div class="left-side">
            <div class="logo">
                <img src="{% static 'login/media/logo-if-branca.png' %}" alt="Instituto Federal Baiano">
                <h1>OBSERV-IF</h1>
            </div>
        </div>
        <div class="right-side">
            <h2>LOGIN</h2>
            <form method="post">
                {% csrf_token %}
                <div class="input-container">
                    <i class="fas fa-user icon"></i>
                    {{ form.username }}
                </div>
                <div class="input-container">
                    <i class="fas fa-lock icon"></i>
                    {{ form.password }}
                </div>
                {% if form.errors %}
                    <div class="alert alert-danger">
                        {% for error in form.non_field_errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
                <button type="submit">ENTRAR</button>
            </form>       
        </div>
    </div>
    <script src="https://kit.fontawesome.com/seu-codigo-font-awesome.js" crossorigin="anonymous"></script>
</body>

</html>

apps/login/templates/login/partials/head.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/brands.min.css" integrity="sha512-58P9Hy7II0YeXLv+iFiLCv1rtLW47xmiRpC1oFafeKNShp8V5bKV/ciVtYqbk2YfxXQMt58DjNfkXFOn62xE+g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/fontawesome.min.css" integrity="sha512-v8QQ0YQ3H4K6Ic3PJkym91KoeNT5S3PnDKvqnwqFD1oiqIl653crGZplPdU5KKtHjO0QKcQ2aUlQZYjHczkmGw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/solid.min.css" integrity="sha512-DzC7h7+bDlpXPDQsX/0fShhf1dLxXlHuhPBkBo/5wJWRoTU6YL7moeiNoej6q3wh5ti78C57Tu1JwTNlcgHSjg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'login/css/index.css' %}">

apps/login/templates/login/partials/header.html
<header>
    <div class="header-esquerda">
        <button class="menu-toggle">
            <i class="fas fa-bars"></i>
        </button>
        <span class="titulo-sistema">Sistema de Cadastro de GECC</span>
    </div>
    <div class="header-direita">
        <i class="fas fa-bell"></i>
        <i class="fas fa-user-circle"></i>
        <span class="nome-usuario">Márcio Alencar</span>
    </div>
</header>

apps/login/templates/login/partials/menu-lateral.html
<aside class="menu-lateral extendido">
    <div class="logo">
        <img src="{% static 'login/media/logo-if-branca.png' %}" alt="Instituto Federal Baiano" class="logo-expandido">
        <img src="{% static 'login/media/logo-if-branca-reduzida.png' %}" alt="Instituto Federal Baiano" class="logo-recolhido">
        <h1 class="nome-sistema">SiSGECC</h1>
    </div>
    <nav>
        <ul>
            <li class="has-tooltip">
                <a href="#">
                    <i class="fas fa-home"></i>
                    <span class="menu-texto">Início</span>
                </a>
                <div class="tooltip">Início</div>
            </li>
            <li class="has-tooltip">
                <a href="#">
                    <i class="fas fa-tasks"></i>
                    <span class="menu-texto">Processos</span>
                </a>
                <div class="tooltip">Processos</div>
            </li>
            <li class="has-tooltip">
                <a href="{% url 'login:logout' %}">
                    <i class="fas fa-sign-out-alt"></i>
                    <span class="menu-texto">Sair</span>
                </a>
                <div class="tooltip">Sair</div>
            </li>
        </ul>
    </nav>
</aside>

apps/painel/templates/painel/pages/painel copy.html
{% extends "global/pages/master-page.html" %}
{% load static %}

<title> OBSERVIF | {% block title %} Painel {% endblock title %} </title>

{% block conteudo %}
<div class="dashboard-container">
    <!-- Cartão 1 -->
    <div class="dashboard-card">
        <h3>Dashboard 1</h3>
        <p>Resumo do Dashboard 1. Este dashboard apresenta dados sobre...</p>
        <button class="dashboard-link" onclick="showDashboard('dashboard1')">Acessar Dashboard</button>
    </div>

    <!-- Cartão 2 -->
    <div class="dashboard-card">
        <h3>Dashboard 2</h3>
        <p>Resumo do Dashboard 2. Este dashboard apresenta dados sobre...</p>
        <button class="dashboard-link" onclick="showDashboard('dashboard2')">Acessar Dashboard</button>
    </div>

    <!-- Cartão 3 -->
    <div class="dashboard-card">
        <h3>Dashboard 3</h3>
        <p>Resumo do Dashboard 3. Este dashboard apresenta dados sobre...</p>
        <button class="dashboard-link" onclick="showDashboard('dashboard3')">Acessar Dashboard</button>
    </div>


<!-- Bloco para exibir o dashboard -->
<div id="dashboard-display" class="dashboard-display" style="display: none;">
    <iframe id="dashboard-iframe" src="" width="100%" height="500" frameborder="0" allowfullscreen></iframe>
</div>

{% endblock conteudo %}






{% block javascript %}
    <script src="{% static 'login/js/script.js' %}"></script> 
{% endblock javascript %}

apps/painel/templates/painel/pages/painel.html
{% extends "global/pages/master-page.html" %}
{% load static %}

<title> OBSERVIF | {% block title %} Painel {% endblock title %} </title>

{% block conteudo %}
<h4 class='titulo-sessao-principal'>LISTA DE DASHBOARDS</h4>
<hr class='linha-verde'>
<div class="dashboard-container">

    {% for dashboard in dashboards %}
        <div class="dashboard-card">
            <h3>{{ dashboard.nome }}</h3>
            <p>{{ dashboard.descricao|slice:":100" }}...</p>
            <a href="{% url 'painel:dashboard' dashboard.id %}" class="dashboard-link">Acessar Dashboard</a>
        </div>
    {% endfor %}

</diV>
{% endblock conteudo %}


{% block javascript %}
    <script src="{% static 'login/js/script.js' %}"></script> 
{% endblock javascript %}

apps/painel/templates/painel/partials/dashboard.html
{% extends "global/pages/master-page.html" %}
{% load static %}

<title> OBSERVIF | {% block title %} Painel {% endblock title %} </title>

{% block conteudo %}
<h4 class='titulo-sessao-principal'>{{ dashboard.nome|upper }}</h1>
<hr class='linha-verde'>

<div class="dashboard-page">
    <!-- Coluna da esquerda: Detalhes do Dashboard -->
    <div class="dashboard-details">
        <h3>Detalhes do Dashboard</h3>
        <hr class='linha-verde linha-reduzida'>
        <p><strong>Descrição:</strong> {{ dashboard.descricao }}</p>
        <p><strong>Origem dos Dados:</strong> {{ dashboard.fonte_dos_dados }}</p>
        <p><strong>Aplicação Prática:</strong> {{ dashboard.utilizacao|safe }}</p>
        <p><strong>Última Atualização:</strong> {{ dashboard.data_atualizacao|date:"d/m/Y" }}</p>
    </div>

    <!-- Coluna da direita: Dashboard -->
    <div class="dashboard-display">
        <iframe 
            src="{{ dashboard.link }}" 
            width="100%" 
            height="500" 
            frameborder="0" 
            allowfullscreen>
        </iframe>
    </div>
</div>

<!-- Bloco para exibir o dashboard -->
<div id="dashboard-display" class="dashboard-display" style="display: none;">
    <iframe id="dashboard-iframe" src="" width="100%" height="500" frameborder="0" allowfullscreen></iframe>
</div>
{% endblock conteudo %}






{% block javascript %}
    <script src="{% static 'login/js/script.js' %}"></script> 
{% endblock javascript %}